### PR TITLE
Fix: jwt bearer events

### LINKED ISSUE #106: Refresh token not working when Token is expired
I'm rewriting this issue here again because my previous findings may not be correct. To simulate this issue I set the JWT Token to expire in 2 minutes in order to test the refresh token.

image

Run the application and Login using the default mukesh@blazorhero.com  account. Wait for about 3 to 5 minutes then click on any menu item e.g.  "User",  the application will failed and you are forced logout and redirect to the login screen. Since the RefreshToken is valid for 7 days, the application should be able to get a new JWT Token instead of crashing out. See screen shots below. 

image
   
 
```
dotnet.5.0.6.js:1 POST https://localhost:5001/api/identity/token/refresh net::ERR_HTTP2_PROTOCOL_ERROR 500
dotnet.5.0.6.js:1 POST https://localhost:5001/api/identity/token/refresh net::ERR_HTTP2_PROTOCOL_ERROR 500
dotnet.5.0.6.js:1 GET https://localhost:5001/api/identity/user 500
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'M' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorHero.CleanArchitecture.Shared.Wrapper.Result`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], BlazorHero.CleanArchitecture.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorHero.CleanArchitecture.Shared.Wrapper.Result`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], BlazorHero.CleanArchitecture.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Result`1](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Result`1](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[Result`1](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[Result`1](String json, JsonSerializerOptions options)
   at BlazorHero.CleanArchitecture.Client.Infrastructure.Extensions.ResultExtensions.<ToResult>d__0`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Client.Infrastructure\Extensions\ResultExtensions.cs:line 14
   at BlazorHero.CleanArchitecture.Client.Infrastructure.Managers.Identity.Users.UserManager.GetAllAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Client.Infrastructure\Managers\Identity\Users\UserManager.cs:line 24
   at BlazorHero.CleanArchitecture.Client.Pages.Identity.Users.GetUsersAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Pages\Identity\Users.razor.cs:line 26
   at BlazorHero.CleanArchitecture.Client.Pages.Identity.Users.OnInitializedAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Pages\Identity\Users.razor.cs:line 21
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### PR DESCRIPTION
**Pull request by unchase**
* Fix #106 (when refresh token is expired):

token_expired

* Add generic `IEntity<TId>` and `IAuditableEntity<TId>` to factor in non integer id's (update all related classes)
* Fix saving `AuditEntry` when modify the some auditable Entity:

image

* Add validation that barcode already exists when creating the `Product`:

image

* Add *All Permissions* tab with all permissions to `RolePermissions` page:

all_permissions

### CODE REVIEW

**Comment by unchase** [comment]
@iammukeshm ready for review!

**Comment by neozhu** [comment]
Usually, Private variables Naming Conventions are by underscore and lowercase name?

**Comment by unchase** [comment]
> Usually, Private variables Naming Conventions are by underscore and lowercase name?

Usually yes. However, for properties, the naming convention is capitalized.
Class members marked with the `Inject` attribute must be properties. Because of this limitation, I use this naming convention

**Comment by iammukeshm** [comment]
Hi, found many bugs in the commits.
1. Name cards take time to load?
2. Permission Page missing
3. the UI for tables still has overlapping issues.

Could you check?

**Comment by unchase** [comment]
> Hi, found many bugs in the commits.
> 
> 1. Name cards take time to load?
> 2. Permission Page missing
> 3. the UI for tables still has overlapping issues.
> 
> Could you check?

Hi, @iammukeshm 

1. What do you mean?

2. Did you use `drop-database` and then `update-database` after merging? The user with **Administrator** role should has a concrete permission to see the `RolePermissions` page (and related action named **Manage Permission**):

image
 
image
 
 You can add this permission without database dropping manually:
 
image
 
3. Related to the https://github.com/Garderoben/MudBlazor/issues/1586. It's not a bug. We can fix only the one issue - https://github.com/blazorhero/CleanArchitecture/issues/118 or Actions menu overlapping (since both issues depend on one css property `overflow` in the `.mud-table-container` class):

image

image

I chose fixing the second.

**Comment by unchase** [comment]
@iammukeshm Can you explain the first point?

**Pull request merged**
