### PR TITLE
Fix: Add excel filtered export and other small fixes

### LINKED ISSUE #105: can you  move  the menu button position ？
image

### LINKED ISSUE #106: Refresh token not working when Token is expired
I'm rewriting this issue here again because my previous findings may not be correct. To simulate this issue I set the JWT Token to expire in 2 minutes in order to test the refresh token.

image

Run the application and Login using the default mukesh@blazorhero.com  account. Wait for about 3 to 5 minutes then click on any menu item e.g.  "User",  the application will failed and you are forced logout and redirect to the login screen. Since the RefreshToken is valid for 7 days, the application should be able to get a new JWT Token instead of crashing out. See screen shots below. 

image
   
 
```
dotnet.5.0.6.js:1 POST https://localhost:5001/api/identity/token/refresh net::ERR_HTTP2_PROTOCOL_ERROR 500
dotnet.5.0.6.js:1 POST https://localhost:5001/api/identity/token/refresh net::ERR_HTTP2_PROTOCOL_ERROR 500
dotnet.5.0.6.js:1 GET https://localhost:5001/api/identity/user 500
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'M' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorHero.CleanArchitecture.Shared.Wrapper.Result`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], BlazorHero.CleanArchitecture.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorHero.CleanArchitecture.Shared.Wrapper.Result`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], BlazorHero.CleanArchitecture.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Result`1](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Result`1](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[Result`1](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[Result`1](String json, JsonSerializerOptions options)
   at BlazorHero.CleanArchitecture.Client.Infrastructure.Extensions.ResultExtensions.<ToResult>d__0`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Client.Infrastructure\Extensions\ResultExtensions.cs:line 14
   at BlazorHero.CleanArchitecture.Client.Infrastructure.Managers.Identity.Users.UserManager.GetAllAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Client.Infrastructure\Managers\Identity\Users\UserManager.cs:line 24
   at BlazorHero.CleanArchitecture.Client.Pages.Identity.Users.GetUsersAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Pages\Identity\Users.razor.cs:line 26
   at BlazorHero.CleanArchitecture.Client.Pages.Identity.Users.OnInitializedAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Pages\Identity\Users.razor.cs:line 21
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### PR DESCRIPTION
**Pull request by unchase**
* Add excel filtered export for `Products`, `AuditTrails` and `Users`.
* Fix #106 (JWT-token refresh error).
* Add `LanguageSelector` for mobile view.
* Some code refactoring.
* Fix #105:
image

---

image

### CODE REVIEW

**Comment by unchase** [comment]
@iammukeshm Ready For review!

**Comment by unchase** [comment]
@iammukeshm Ready for review!

**Review by TheCoolestEver — COMMENTED** [review]
What do I ado

**Comment by unchase** [comment]
> What do I ado

?

**Pull request merged**
