### PR TITLE
add ProgressCircular in ImportExcelModal

### PR DESCRIPTION
**Pull request by neozhu**
review it, please.
image

### CODE REVIEW

**Comment by unchase** [comment]
Should fix indented in the code

**Comment by neozhu** [comment]
I know that  I config the 2 space indented format.
so, I suggest that add a .editorconfig file to the solution items to define code style.

**Comment by unchase** [comment]
Anyway you should fix this in the PR before merge it.

**Comment by neozhu** [comment]
fixed.

**Pull request merged**
