### PR TITLE
Feat: Add role permissions grouping, add BlazorHeroRole, show users online status and more other...

### LINKED ISSUE #129: show user online/offline status for contacts list in chat module?
like this that show user online status for chat function.
image

### PR DESCRIPTION
**Pull request by unchase**
* Add role permissions grouping:

grouping_role_permissions

* Update MudBlazor nuget-package
* Fix `SaveChangesAsync` in `BlazorHeroContext` (use `IAuditableEntity` instead of `AuditableEntity`)
* Add auditable `BlazorHeroRole` with `Description` property (**need to use `update-database` in Package Manager Console**):

image

image

image

* Show users online status (Fix #129)

user_online_status

* Add server side localization - add `ServerStorageService` (`ServerStorageProvider` not implemented yet)
*  Fix application localization

### CODE REVIEW

**Comment by unchase** [comment]
@iammukeshm ready for review!

**Comment by neozhu** [comment]
The main navigation menu item and group name are configurable not like hard code?  
Is there a good way to implement?

**Comment by neozhu** [comment]
> @iammukeshm ready for review!

That's a great point, If the number of modules is more than 10 or more configuration will be not easy.

**Comment by chhinsras** [comment]
@unchase  what about treeview as well?

**Comment by unchase** [comment]
> The main navigation menu item and group name are configurable not like hard code?
> Is there a good way to implement?

We have to set permissions in the code in the form of constants, since they are used in attributes.

**Comment by unchase** [comment]
> @unchase what about treeview as well?

TreeView is functionally less convenient than tabular view with filtering and sorting capabilities.

**Comment by TheCoolestEver** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by unchase** [comment]
@iammukeshm ready for review now!

**Comment by iammukeshm** [comment]
Nice additions. 👍

**Comment by iammukeshm** [comment]
image


Could you cross-check this UI issue as well @unchase ?

**Comment by unchase** [comment]
> image
> 
> Could you cross-check this UI issue as well @unchase ?

Fixed in #137. Related to https://github.com/Garderoben/MudBlazor/issues/1586

**Pull request merged**
