### PR TITLE
add Khmer translation (km_KH)

### PR DESCRIPTION
**Pull request by chhinsras**

### CODE REVIEW

**Review by chhinsras — COMMENTED** [review]
khmer translation added

**Comment by iammukeshm** [comment]
Thanks! You will have to add more of this later on when the project is done ;D

**Comment by chhinsras** [comment]
I am committed for this . Will update it accordingly

**Comment by chhinsras** [comment]
also, I would like to embed font. otherwise, it looks not so good on deafult font

**Pull request merged**
