### PR TITLE
add excel import feature

### PR DESCRIPTION
**Pull request by neozhu**
import data from upload excel.
https://user-images.githubusercontent.com/1549611/125552199-6eae7dde-82a5-4098-9b6e-b59708baf276.mp4

### CODE REVIEW

**Comment by neozhu** [comment]
@unchase 
please review it

**Comment by unchase** [comment]
> @unchase
> please review it

@neozhu reviewed in https://github.com/neozhu/CleanArchitecture/pull/1
Just merge it

**Comment by iammukeshm** [comment]
1. What happens when you try to import from a excel file with invalid columns?
2. What happens when you try import data that is already present in the db? How is it handled?
@neozhu

**Comment by unchase** [comment]
> 1. What happens when you try to import from a excel file with invalid columns?
> 2. What happens when you try import data that is already present in the db? How is it handled?
>    @neozhu

@iammukeshm 
1. See:

import_brands

image

2. It handled by `IValidator<AddEditBrandCommand>` in `ImportBrandsCommandHandler` when we try to add imported brands for each brand.

```csharp
//...
private readonly IValidator<AddEditBrandCommand> _addBrandValidator;
// ...

var errors = new List<string>();
var errorsOccurred = false;
foreach(var item in result)
{
    var validationResult = await _addBrandValidator.ValidateAsync(_mapper.Map<AddEditBrandCommand>(item), cancellationToken);
    if (validationResult.IsValid)
    {
        await _unitOfWork.Repository<Brand>().AddAsync(item);
    }
    else
    {
        errorsOccurred = true;
        errors.AddRange(validationResult.Errors.Select(e => $"{(!string.IsNullOrWhiteSpace(item.Name) ? $"{item.Name} - " : string.Empty)}{e.ErrorMessage}"));
    }
}

if (errorsOccurred)
{
    return await Result<int>.FailAsync(errors);
}

//...
```

**Comment by iammukeshm** [comment]
Perfect.

**Comment by peteryulius** [comment]
I found error when import with not matching columns. For example in the Brand table there are Id, Name, Description and Tax, I try to remove the Tax column and then do the process import. Maybe it's should validation mapping before process import.

**Comment by neozhu** [comment]
image
On the left window is the field mapping, right window is validation

**Comment by peteryulius** [comment]
Awesome, that's great for row data validation, but can we validation on column? May be, if the column in excel file not matching with the table on database, show the error message, before do the process import. On the Brand table there are, Id, Name, Description and Tax, but what happen if the column in file excel only have Id, Name and Description. It's show message that column is not matching.

**Comment by unchase** [comment]
@peteryulius fixed in https://github.com/blazorhero/CleanArchitecture/pull/237

**Pull request merged**
