### PR TITLE
Feat: Add document type and generic entity extended attributes

### LINKED ISSUE #171: Search in tables not working as expected when there are several pages.
**Describe the bug**
Search functionality in tables is not working as expected, it does filter and show the elements which are currenty displayed in the list, but not the ones that are in a different page of the table.

**To Reproduce**
1. Go to Products (having more than 10 records so that there are more than one page of results in the table)
2. Search for a Product that is in a different page than the current one, e.g. page 2.
4. The records matching the searched string won't show up, the table will be empty, you will only see them if you go to the page where they are.

**Expected behavior**
The records matching the search string should be shown doesn't matter in which page of the table they are.

### LINKED ISSUE #187: Some bugs occured when running the project
**1. Dashboard**
When adding any new product, to the dashboard, the client-side will display duplicate Products and Bands every time it is added. If add 10 products, it will show 10 times like that.
image

**2. Chat**
I think this is a bug, not a feature. If a user has just registered an account but has not yet authenticated the email or the user is not activated. The chat section will list all users in the database. I think we better improve this function.

- Show only activated users
- Or only admin can chat with all users, and users can only chat with admin or manager.
- Or users can create their own chat rooms

image

If the user sends the message many times, but no one has replied. I think all the messages should be combined. Instead of each message having to display the avatar, username, time...

image

### PR DESCRIPTION
**Pull request by unchase**
#### * Add `DocumentType` auditable entity:

image

* `DocumentType` permissions: 

image

* Add `DocumentType`:

image

* Adding `Document` with required `DocumentType`:

image

---

#### * Add validation that name already exists when creating the document type

---

#### * Fix #171 (also fix searching documents)

---

#### * Add generic interfaces, classes and blazor-components for entity auditable extended attributes (**add new DB migration**). Register extended attributes handlers using reflection

---

#### * Add `Document` extended attributes (`DocumentExtendedAttribute`):

* **Manage Extended Attributes** for the `Document`:

image

* `Document` extended attributes page:

image

* Update extended attribute:

image

* Add extended attribute:

image

* Filter extended attributes in **Security** group:

image

* Filtered extended attributes exporting to excel:

image

image

* `DocumentExtendedAttribute` permissions:

image

---

#### * Add global `Error` blazor-component

---

#### * Fix exporting to excel (use `Result<string>` instead of `string` in response)

---

#### * Fix formatting dates with current culture:

image

---

#### * Add method for getting `Document` by Id:

image

---

#### * Add **No Allowed Actions** button instead of **Actions** if you have not action's permissions (for all pages and entities):

image

---

#### * Add *Permissions.\*.Export* permissions for all exported entities:

image

---

#### * Add `AutoFilter` and `AutoFitColumns` for excel exporting:

image

---

#### * Add *Permissions.\*.Search* permissions for all entities:

image

---

#### * Add *MudProgressCircular* for all pages if data is not loaded yet:

loaded

---

#### * Logout the user if user not found for current userId (gotten from stored token):

logged_out

P.S. For example, after manual deleting the user or dropping DB.

---

#### * Fix #187 (1):

dashboards

---

#### * Fix #187 (2):

chat

---

#### * Add `Document`, `DocumentType`, `DocumentExtendedAttribute` dashboard values:

image

---

#### * Add small fixes and localization, remove unused classes...

### CODE REVIEW

**Comment by neozhu** [comment]
I would like to suggest that provide a dictionary entity(key, value, typename, description), specifically for the drop-down or autocomplete control to provide as data source?

**Comment by unchase** [comment]
Hi, @neozhu

What are the benefits of this?

**Comment by neozhu** [comment]
> Hi, @neozhu
> 
> What are the benefits of this?
In real business scenario one entity like order information include e.g. "Status", "Unit","Currency",.. enum-type, maintain one  dictionary（table） is simpler then create entity of each field. I think
:)

**Comment by unchase** [comment]
I think that this can be conditionally called *extended attributes* of an **entity**. You can add such extended attributes to any entity that has a specific interface. All in all a good idea. I'll think about its implementation.

**Comment by neozhu** [comment]
@unchase 
Haha, you know what I mean. :)

**Comment by unchase** [comment]
But if we want to store all such extended attributes in one table in DB, we will have an issue with performance when the count of entities with its attributes becomes large.
So we should add a one table for one entity with extended attributes.
@iammukeshm what do you think?

**Comment by neozhu** [comment]
If you can be implemented configurable and dynamically append/extended new attributes/fields in one entity. it's wonderful.
as a production development platform, this feature is very useful. right?

**Comment by unchase** [comment]
Right. But what about performance?

**Comment by neozhu** [comment]
@unchase 
I think not worried about performance, in the usual case there won't be a lot of data on one project. But it can greatly reduce the development effort.
if has a big data situation, it is necessary to create a new table.

**Comment by unchase** [comment]
In my opinion, when adding a new entity, you should consider whether it needs extended attributes. If necessary, then immediately add the entity of extended attributes to it (in this case, any number of values for the added entity can be stored in the extended attributes).
Thus, we will add two tables in the event that the new entity needs extended attributes, and one table - if not.

This will partially solve the performance problem and separate extended attributes for different entities at the database level.

**Comment by supermun** [comment]
> Thus, we will add two tables in the event that the new entity needs extended attributes, and one table - if not.

Hi @unchase , what about if 2 or more entities have the same extended attributes?

**Comment by unchase** [comment]
> Hi @unchase , what about if 2 or more entities have the same extended attributes?

Hi, @supermun 
In this case, it is better to create two independent records in two tables (one for each entity).

First, when deleting a specific entity, all of its extended attributes will be cascade deleted.
Secondly, when using one table, we need an additional field indicating belonging to a certain entity (s), otherwise how to search for all extended attributes for some entity? Or there must be a staging table that links the entity to the extended attribute.
Thirdly, when using a single table, performance will decrease over time, as the number of records will grow dramatically. There will be no such problem in various tables.

**Comment by supermun** [comment]
> Hi, @supermun
> In this case, it is better to create two independent records in two tables (one for each entity).
> 
> First, when deleting a specific entity, all of its extended attributes will be cascade deleted.
> Secondly, when using one table, we need an additional field indicating belonging to a certain entity (s), otherwise how to search for all extended attributes for some entity? Or there must be a staging table that links the entity to the extended attribute.
> Thirdly, when using a single table, performance will decrease over time, as the number of records will grow dramatically. There will be no such problem in various tables.

I'm sorry, maybe I'm misunderstanding. As @neozhu said:
>In real business scenario one entity like order information include e.g. **"Status", "Unit","Currency"**,.. **enum-type**
--> Eg: **"Currency"**: include: USD, EURO, JPY...
**"Status"**: include: Pending, Confirmed , Shipped...

 If you add all of them into a table, 
1. how can you show the drop-down or autocomplete control to provide as data source for each field?
2. what about if end user want to insert / remove a record in extended attributes table?
3. Records in some extended attributes table maybe difference because of input error( maybe), so you cannot search for all extended attributes for some entities.
4. In my opinion, we should have only 1 table like this:
Screenshot 2021-06-10 082812

Screenshot 2021-06-10 083123

5. If you wonder about performance, you can create 2 or more table SYSCODE  for each "data area".

**Comment by neozhu** [comment]
@supermun 
Your implementation is too complicated, I suggest that business entities not establish foreign key relationships with sys code entities.  
SysCode Table save data only provide data source for dropdown control and autocomplete control. simpler?

**Comment by supermun** [comment]
> @supermun
> Your implementation is too complicated, I suggest that business entities not establish foreign key relationships with sys code entities.
> SysCode Table save data only provide data source for dropdown control and autocomplete control. simpler?

Hello @neozhu 
It's just an example only to demonstrated the relationship between syscode and business entity. The foreign key is established or not is based on your application.

**Comment by Sharafudeen** [comment]
Hi,

I have an idea to proceed @neozhu suggestions.

1. Create an entity called EntityType which will have (Id, Name, Description) fields
2. Create an entity called EntityTypeValues which will have (Id, EntityTypeId, Values) fields
3. Values can be store one or more entries as a JSON format
4. Any list of data such as Country, Currency, Unit Of Measure, Status, etc., can be stored in this table
5. Since database table will have only one record for each entities then it will not have any performance issues

**_Note:_** _We can update only Values field record if user add or update or delete any of an **EntityType**._

Any thoughts?

**Comment by neozhu** [comment]
@Sharafudeen 
Great, Your idea is very good.
1, JSON data how to import from excel, Usually this is the kind of data that the user wants to maintain in Excel and then import into the system at once, or develop, Migrate the test environment to the production environment, it's probably going to use Excel export/import.
Do you have any good ideas on the above questions?

**Comment by Sharafudeen** [comment]
> @Sharafudeen
> Great, Your idea is very good.
> 1, JSON data how to import from excel, Usually this is the kind of data that the user wants to maintain in Excel and then import into the system at once, or develop, Migrate the test environment to the production environment, it's probably going to use Excel export/import.
> Do you have any good ideas on the above questions?

Can you elaborate more about your question? What do you mean import JSON data?

You can read Excel sheet and convert into JSON format. Entity names should be imported into EntityType table and data will be stored into EntityTypeValues table. To Export data, you can convert JSON into your Excel format.

**Comment by unchase** [comment]
@neozhu @Sharafudeen @supermun 
I am working on the implementation of extended attributes now, I will provide my solution for this issue soon.

**Comment by unchase** [comment]
> Hi,
> 
> I have an idea to proceed @neozhu suggestions.
> 
> 1. Create an entity called EntityType which will have (Id, Name, Description) fields
> 2. Create an entity called EntityTypeValues which will have (Id, EntityTypeId, Values) fields
> 3. Values can be store one or more entries as a JSON format
> 4. Any list of data such as Country, Currency, Unit Of Measure, Status, etc., can be stored in this table
> 5. Since database table will have only one record for each entities then it will not have any performance issues
> 
> **_Note:_** _We can update only Values field record if user add or update or delete any of an **EntityType**._
> 
> Any thoughts?

This solution has its drawbacks:

1. How do we differentiate access to work with extended attributes of different entities? For example, I want to allow the user to change extended attributes for `Entity1`, but disallow for `Entity2`.
2. How to associate values ​​in the **EntityType** table with specific entity classes? We can add a new value to the **EntityType** table, but it will not be associated with the entity class.
3. What if we don't need all the values ​​from the *Json* string stored in the table, but only a small part? What about data consistency when many users try to change different fields in *json* for one entity at the same time?

**Comment by Sharafudeen** [comment]
> This solution has its drawbacks:
> 
> 1. How do we differentiate access to work with extended attributes of different entities? For example, I want to allow the user to change extended attributes for `Entity1`, but disallow for `Entity2`.
> 2. How to associate values ​​in the **EntityType** table with specific entity classes? We can add a new value to the **EntityType** table, but it will not be associated with the entity class.
> 3. What if we don't need all the values ​​from the _Json_ string stored in the table, but only a small part? What about data consistency when many users try to change different fields in _json_ for one entity at the same time?

As we know, we have following approach:

1. **EAV pattern** = Entity Attribute Value
2. **NoSQL pattern** = Document based data store. Now a days, almost every ecommerce applications using this pattern. Because it is more extensible for products attributes and so on.. NoSQL databases are using this technique.

I'm suggesting NoSQL pattern.

The answer for your above questions are.. you can add multiple records for each EntityType in **EntityTypeValues table**. Of course, JSON data stored repeatedly but not duplicated records. In this way, you can extend your attributes for specific EntityType.

How do you link Country and its Value in User table?
- You can add three foreign keys in User. They are, CountryId (EntityTypeId), EntityTypeValuesId and Id (from JSON data) and these fields from EntityTypeValues table.

**Comment by neozhu** [comment]
Sorry, I am not good at English.
You're getting a little complicated,
So there are two problems that if you have a good solution.
1. In order to facilitate the user to select data instead of keyboard key-in when adding/editing data, such as status, gender, currency, unit ...,  I think it is enough to provide the maintenance dictionary table( typeName, key, value) 
2. Dynamically extend properties for the entity,  configurable, scenario one: e-commerce product table,  need to be extended entity properties.
The above two can be achieved at the same time, very difficult

**Comment by unchase** [comment]
@iammukeshm ready for review!

**Comment by iammukeshm** [comment]
could you fix the conflicts @unchase

**Comment by unchase** [comment]
> could you fix the conflicts @unchase

Working on it...

**Comment by unchase** [comment]
@iammukeshm ready to merge i think

**Review by iammukeshm — APPROVED** [review]

**Pull request merged**
