### PR TITLE
add delete checked rows feature

### PR DESCRIPTION
**Pull request by neozhu**
Please, review it.
https://user-images.githubusercontent.com/1549611/126422384-9dc020ea-0a10-4cc5-8c23-0700a73a0cdc.mp4
<video src="https://user-images.githubusercontent.com/1549611/126422384-9dc020ea-0a10-4cc5-8c23-0700a73a0cdc.mp4" controls="controls" width="500" height="300"></video>

### CODE REVIEW

**Comment by unchase** [comment]
@neozhu Should fix indented in the code

**Comment by peteryulius** [comment]
hi @neozhu it's nice feature, great.

I'm modifying the code like below:

**Brands.razor.cs**

image

image


**Brands.razor**
image

How about this modified code?
To ensure that the _selectedItems equal null when the _selectedItems.Count > 0.

**Comment by neozhu** [comment]
it's ok,
you know that mudtable MultiSelection feature when using server-side pagination, click check selected all, check all current rows, but table head checkbox not selected, then I want unselected all that not working.

**Comment by peteryulius** [comment]
> you know that mudtable MultiSelection feature when using server-side pagination, click check selected all, check all current rows, but table head checkbox not selected, then I want unselected all that not working.

Do you mean on Products? I'm not yet updated my project with this feature on the products.

**Comment by neozhu** [comment]
@peteryulius  you try it when data is more than page size(10).  when two pages data

**Comment by peteryulius** [comment]
> @peteryulius you try it when data is more than page size(10). when two pages data

Ok, I'll try later.

**Comment by neozhu** [comment]
that performance issue please check again.thank you

**Comment by peteryulius** [comment]
> @peteryulius you try it when data is more than page size(10). when two pages data

May be it's bugs on the components.

You has send the issue on github.
https://github.com/Garderoben/MudBlazor/issues/2295

**Pull request closed without merging**
