### PR TITLE
Add more Russian localization

### PR DESCRIPTION
**Pull request by unchase**

### CODE REVIEW

**Comment by iammukeshm** [comment]
Thanks! Any feedback on 2.0?

**Comment by unchase** [comment]
> Thanks! Any feedback on 2.0?

* **LOCALIZATION**:

- [ ] Should to provide localized validation messages for validation attributes. Example:

image

Probably with:

```csharp
[Required(ErrorMessageResourceName = "<Key>", ErrorMessageResourceType = typeof(ResourceType))]
```

- [ ] Should localize [this strings](https://github.com/hoaint235/CleanArchitecture/blob/3b6bc7112f5e8b8d7fada2382bea0c0a913041e3/BlazorHero.CleanArchitecture.Infrastructure/Services/AuditService.cs#L42-L48)

---

* **COMMON**:

- [ ] You can make this button clickable so that when we click on it, the user profile opens.

image

- [ ] I can't download the added file with **Download** button in Actions. Nothing happens:

image

- [ ] Add icon to the **EXPORT** button (probably should rename to **EXPORT TO EXCEL**):

image

like in *Audit Trails*:

image

- [ ] You can add the **Upload** button here:

image

- [ ] Need to add email confirmation after registration the new user (can't login):

image

- [ ] You can add more [Authentication providers](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-5.0&tabs=visual-studio), [AspNet.Security.OAuth.Providers](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers), [AspNet.Security.OpenId.Providers](https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers).
- [ ] You can add a telegram-bot interaction (send some notifications)

---

* **CHAT**

- [ ] You can add the **EXPORT CHAT** button in the *Chat* page
- [ ] You can add the ability to send some files (docs, images etc.) in the *Chat*

**Comment by iammukeshm** [comment]
What's the issue you face with downloading documents? It seems to be working fine for me. Could you check if you get any exceptions on the console? And also check if the file is copied over to the Files directory under your server project

**Comment by unchase** [comment]
> What's the issue you face with downloading documents? It seems to be working fine for me. Could you check if you get any exceptions on the console? And also check if the file is copied over to the Files directory under your server project

upload

There is no file in Files directory and no exceptions on the console.

**Pull request merged**
