### PR TITLE
Clarify architecture

### PR DESCRIPTION
**Pull request by unchase**
image

* The components were given a clear area of responsibility. 
* Now you don't have to think about what to put in what component. 
* Less likely to make a mistake.

**Project Dependency Diagram:**

Architecture view for BlazorHero CleanArchitecture_4

**Projects hierarchy in Solution Explorer:**

image

### CODE REVIEW

**Comment by unchase** [comment]
@iammukeshm ready for review.

**Comment by iammukeshm** [comment]
Hi, I am not actually very thrilled with this extend of project separation. It May not be preferred by most of the developers. The idea was to keep the project clean, yet very simple. However, I will take some time and look into it.

**Comment by unchase** [comment]
Hi @iammukeshm

In fact, the project remains as simple and clean. Only visually it seems that it has become more complicated, as the number of projects in the solution has increased.

However, this approach has several advantages:

* First, we have a clear atomic separation of contexts and components, and there is no need to think about where to put them when adding new functionality or new components.
* Secondly, the area of ​​responsibility of each component is more clearly defined due to the fact that, for example, any service implementation refers only to its own interface (there are no references to a common project with all interfaces). That is, it is more difficult to make an error in the code (call the wrong method, etc.).
* Thirdly, when developing different teams of different services, there is no need to change the code in one project - all services are separated at the project level. Accordingly, it is easier to merge changes into a common branch for several teams.
* Fourthly, on the contrary, it is easier for developers to familiarize themselves with such a solution structure, since it is more atomic and the classes are located in those components where they are guaranteed to be used.

**Comment by iammukeshm** [comment]
I agree with your points. My main concern is that following this structure, adding new features would be an issue visually, as devs would have to ideally follow the same structure for adding new features and services. This would become a nightmare in complete applications. RoleService / ExcelService and so on... But that's my first thought only. will check

**Comment by unchase** [comment]
The only difference is that instead of adding a new service class within one project, a new project will be added for a new service.
In addition, I don’t think that in most real projects the number of such services is more than a ten :)

For me, for example, it is easier to visually abstract from other services in a separate project, without fear of influencing other services with my changes, as if they were in the same project.

You can additionally group services in your layers by different directories. Visually, this will be almost no different from how it is done now.

image

Well, in conclusion, we can use the ability to unload individual projects from the solution, which we do not need for the current development (when developing for different hosts - web or mobile or another, - that use different components). Visual Studio allows us to do this. When placing all services in one project, this will not work :)

**Comment by unchase** [comment]
Hi, @iammukeshm 
What do you think in the end of this implementation of a clean architecture, taking into account all its advantages and disadvantages?

**Comment by scottkuhl** [comment]
I would tend to agree with @iammukeshm in that this would not be preferred by most developers.  I would expect many developers looking for a clean architecture approach to Blazor would have some experience with the [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb) solution and the [Jason Taylor Clean Architecture](https://github.com/jasontaylordev/CleanArchitecture) solution.  This repo is currently very similar to those, allowing a lot of knowledge and comfort transition.

**Comment by iang0ld** [comment]
This is an interesting comment.  When I first saw this repo I was looking at adding Blazor to the Jason Taylor solution which I have used before.  What was the inspiration for starting fresh and not just building on top of Jason work?

**Comment by unchase** [comment]
> I would tend to agree with @iammukeshm in that this would not be preferred by most developers. I would expect many developers looking for a clean architecture approach to Blazor would have some experience with the eShopOnWeb solution and the Jason Taylor Clean Architecture solution. This repo is currently very similar to those, allowing a lot of knowledge and comfort transition.

I understand your position, and I partially agree with it.
However, there are many arguments in favor of the approach I propose, which I mentioned above.
In the Russian-speaking community, there are specialists [Andrei Tsvettsikh](https://dotnext-piter.ru/en/2021/spb/people/#3Iujn3OqUiVPnK3YmOYVp3) and [Denis Tsvettsikh](https://dotnext-piter.ru/en/2021/spb/people/#5goUPM5GE0saG0YMmWU6sE) who speak at the largest .net conference - [dotnext](https://dotnext.ru/en/) (and more other conferences) and show ([video 1](https://www.youtube.com/watch?v=jxoAokHIsc0), [video 2](https://www.youtube.com/watch?v=SazEYHv2IbI)) the flaws of Jason Taylor's architecture.

Unfortunately, videos with their reports exist only in Russian, but I fully support their point of view.
And not always following the already existing project structure (as in the repositories from [Jason Taylor](https://github.com/jasontaylordev/CleanArchitecture) or [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb)) is right.

Sometimes it is useful to break existing approaches in order to grow)

**Comment by chhinsras** [comment]
@unchase  Could you elaborate or show the practical solution being used for this kind of separation. There is no right or wrong for the pattern the code structure. It's just who uses it for which purpose. 

I personally separate only for 4 projects - **_API, Application, Persistence and Client._**  This is good enough for most purposes. The atomic separation of your seems nightmare at first, but it may be very useful for enterprise application like - Facebook , Google. 

Might be there is should be option.

**Comment by unchase** [comment]
@chhinsras You can use this separation in any enterprise project. I gave its advantages earlier, they are valid for any solution.
Since such an architecture is universal for an application of any complexity, when switching to another project with such an architecture, it is easier for a programmer to adapt.

**Comment by scottkuhl** [comment]
> Since such an architecture is universal for an application **of any complexity**

This is the one part I would disagree with.  The proposed changes would be overkill for small to medium complexity applications.  However, this entire solution could be argued to be too complex for small applications anyway.

I guess my final thought on this can be summed up like this, if these changes would be made:

1 - I would probably not use this template.
2 - I would not recommend this template to students at our code school for their final projects because it is too different than what they are likely to run into on the job.
3 - Other developers first seeing the repo may be instantly turned off by the number of projects without even giving it a chance.

Perhaps it's better to create a fork of this repo with your proposed changes and see how the adoption rate grows?

Either way, it's an interesting change, and I appreciate the effort to make things better.  It may actually make things more usable in very large projects with multiple bounded contexts split into separate assemblies.  I think that may be the most viable target audience.  But at that point you also start to slip into micro-services and serverless as a better option.

🤷‍♂️

**Comment by scottkuhl** [comment]
> Since such an architecture is universal for an application **of any complexity**

This is the one part I would disagree with.  The proposed changes would be overkill for small to medium complexity applications.  However, this entire solution could be argued to be too complex for small applications anyway.

I guess my final thought on this can be summed up like this:

1 - If these changes would be made, I would probably not use this template.
2 - If these changes would be made, I would definitely not recommend this template to students at our code school for their final projects because it is too different than what they are likely to run into on the job.

Perhaps it's better to create a fork of this repo with your proposed changes and see how the adoption rate grows?

Either way, it's an interesting change, and I appreciate the effort to make things better.

**Comment by chhinsras** [comment]
I do not mean to offend any one. I personally build few projects without any separation. Using only MVC pattern. This is kinda obsolete but, yes, it is depend on the project itself.


Somehow, having 3 separated projects should be okay for most case (API, Application, Client).

**Comment by iammukeshm** [comment]
I too agree with the above point. I hope it doesn't offend anyone. If this is the architecture needed, being in a Monolith design in the first place itself is too wrong. You need to have already moved to Microservice Architecture. My intention with this project was to have a starting point for single-featured applications to an average mid-scale application, which I think is kind of achieved. Although I like the granular separation, this will raise eyebrows for nearly every developer. As @scottkuhl  suggests, even with my project, it might be still an overkill for many small applications.

**Pull request closed without merging**
