### PR TITLE
Fix #95 - add localized validation errors

### LINKED ISSUE #95: The MudTextField`1 field is required. appears as validation message
**Describe the bug**
When trying to create a new Brand item with empty Name\Description the UI displays the The MudTextField`1 field is required. instead of Name is required, Description is required. The same happens on Product, User, etc pages.

**To Reproduce**
1. Go to 'Brands'
2. Click on 'Create'
3. Click into 'Description'
4. See the wrong validation Message.

**Expected behavior**
Name is required, Description is required should be displayed.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge

### PR DESCRIPTION
**Pull request by unchase**
1. Fix #95 (add [FluentValidation](https://fluentvalidation.net/))
2. Add more localization (for all pages, models and its validators), fix some localization, disable submit buttons on not validated pages. For example:

  * Add\Update `Document`:
image
image
  * Add\Edit `Product`:
image
  * Add\Edit `Brand`:
image
  * `Login`:
image
  * `Register`:
image
  * Register new `User`:
image
  * Reset password (`Forgot`):
image
  * Update `Profile`:
image
  * Update `Security`:
image

---

3. Fix document's file uploading for long file size
4. Delete unused code, refactor some blocks of code
5. Reorganize Features folder content to common view
6. Add **Language Selector** and **Dark Mode Toggler** for `NotAuthorized`:

image

### CODE REVIEW

**Comment by unchase** [comment]
@iammukeshm Ready for review!

**Comment by iammukeshm** [comment]
Validation Messages were pending for a really long time now. Thanks for all the changes and effort mate :D

**Comment by unchase** [comment]
> Validation Messages were pending for a really long time now. Thanks for all the changes and effort mate :D

You are welcome)

**Comment by unchase** [comment]
Related to #107

**Pull request merged**
