### PR TITLE
Fix: Import from excel improvements

### PR DESCRIPTION
**Pull request by unchase**
import_brands_improve

### CODE REVIEW

**Comment by TheCoolestEver** [comment]
Unsubscribe my email

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by peteryulius** [comment]
This was extremely helpful man, thanks a lot.

**Comment by gfo2007** [comment]
@unchase hi. This feature is fantastic. Thank you and neozhu. However when I set up a new BlazorHero project, I don't see the import button.

**Comment by unchase** [comment]
Hi @gfo2007 
Can you check your permissions?

**Comment by gfo2007** [comment]
@unchase thanks for your response. 

Please I have checked the administrator permissions and all permissions are granted. Below is the image of the document page. It doesn't show **IMPORT**

No Import Button -  BlazorHero

Regards.

**Pull request merged**
